#!/bin/bash

# Simple script to help create Xcode project
# This provides instructions if automatic creation fails

echo "=========================================="
echo "Notchy Xcode Project Setup"
echo "=========================================="
echo ""
echo "Since automatic project generation may have issues,"
echo "please create the project manually in Xcode:"
echo ""
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Choose 'macOS' → 'App'"
echo "4. Click Next"
echo "5. Fill in:"
echo "   - Product Name: Notchy"
echo "   - Team: (your team or None)"
echo "   - Organization Identifier: com.notchy"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "   - Storage: None"
echo "   - ☑ Use Core Data (uncheck)"
echo "   - ☑ Include Tests (uncheck)"
echo "6. Click Next"
echo "7. Save in: $(pwd)"
echo "8. Click Create"
echo ""
echo "Then add all source files:"
echo "9. Right-click on 'Notchy' folder in Project Navigator"
echo "10. Select 'Add Files to Notchy...'"
echo "11. Navigate to Sources/Notchy/"
echo "12. Select all folders: Models, Managers, Views, Widgets, Utilities"
echo "13. Ensure 'Create groups' is selected"
echo "14. Ensure 'Copy items if needed' is UNCHECKED"
echo "15. Click Add"
echo ""
echo "Configure project settings:"
echo "16. Select 'Notchy' project (blue icon) in Navigator"
echo "17. Select 'Notchy' target"
echo "18. General tab:"
echo "    - Minimum Deployments: macOS 14.6"
echo "19. Build Settings tab:"
echo "    - Search for 'Info.plist File'"
echo "    - Set to: Sources/Notchy/Info.plist"
echo "20. Delete the default ContentView.swift and NotchyApp.swift"
echo "    (we have our own versions)"
echo ""
echo "Then build and run with ⌘R!"
echo ""

