name: Notchy
options:
  bundleIdPrefix: com.notchy
  deploymentTarget:
    macOS: "14.6"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages: {}

targets:
  Notchy:
    type: application
    platform: macOS
    deploymentTarget: "14.6"
    sources:
      - path: Sources/Notchy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notchy.app
        PRODUCT_NAME: Notchy
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Sources/Notchy/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.6"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ""
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: "-O"

schemes:
  Notchy:
    build:
      targets:
        Notchy: all
    run:
      config: Debug
    archive:
      config: Release
